openapi: 3.0.2
info:
  title: FunCode Challenge Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: FeedService
paths:
  /record:
    get:
      tags:
        - Record
      summary: get feed record by id
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: feed record id
          required: true
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtendedFeedRecord'
  /feed:
    get:
      tags:
        - Feed
      summary: get feed list
      parameters:
        - in: query
          name: language
          schema:
            type: string
            default: de
          description: feed language
          required: false
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: limit items on page
          required: false
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          description: current page offset (records)
          required: false
        - in: query
          name: cursor
          schema:
            type: string
          description: pagination cursor
          required: false
        - in: query
          name: since-id
          schema:
            type: string
          description: last id for fetch
          required: false
        - in: query
          name: since-timestamp
          schema:
            type: integer
          description: last timestamp for fetch
          required: false
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedResponse'
components:
  schemas:
    FeedResponse:
      title: FeedResponse
      required:
        - records
      type: object
      properties:
        records:
          type: array
          $ref: '#/components/schemas/FeedRecord'
        metadata:
          $ref: '#/components/schemas/MetaData'
    FeedRecord:
      title: FeedRecord
      type: object
      properties:
        id:
          type: string
          description: record id (unique hash code)
        source-name:
          type: string
          description: source resource name
        timestamp:
          type: integer
          format: int64
          description: record timestamp
        language:
          type: string
          description: media language
        media-type:
          type: string
          description: media type (image, video)
        hash-code:
          type: string
          description: hash of record
        duration:
          type: integer
          description: media duration (seconds)
        title:
          type: string
          description: media title
        description:
          type: string
          description: media description
        tags:
          type: array
          items:
            type: string
            uniqueItems: true
          description: media tags
        size:
          type: integer
          format: int64
          description: media size in bytes
        thumbnail:
          type: string
          format: byte
          description: base64 thumbnail
        external-link:
          type: string
          format: uri
          description: external link to media
        hash-data:
          type: string
          description: computed hash data
    ExtendedFeedRecord:
      title: FeedRecord
      type: object
      allOf:
        - $ref: '#/components/schemas/FeedRecord'
        - type: object
          properties:
            external-id:
              type: string
              description: external (system) record id
            media-link-id:
              type: string
              format: string
              description: storage media link id
            likes-count:
              type: integer
              description: likes counter
            dislikes-count:
              type: integer
              description: dislikes counter
            follow-count:
              type: integer
              description: follow counter
            comment-count:
              type: integer
              description: total comments
            total-views:
              type: integer
              description: total views
            full-text:
              type: string
              description: full text for media (entire post)
            all-headers:
              type: array
              items:
                type: string
                uniqueItems: true
              description: all media item headers
    MetaData:
      title: MetaData
      type: object
      properties:
        cursor:
          type: string
          description: pagination cursor
        page:
          type: integer
          description: current page
        limit:
          type: integer
          description: page limit
        total-records:
          type: integer
          description: total records in storage